# Pandas

In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np 
from pandas import Series, DataFrame

## Series

One dimensional array-like object containing a sequence of values and an associated array of data labels, called its index.


Like a fixed-length, ordered dict, which maps index values to data values.

In [2]:
obj = pd.Series([-1,-2,3,4])

obj

0   -1
1   -2
2    3
3    4
dtype: int64

In [3]:
obj.values

array([-1, -2,  3,  4], dtype=int64)

In [4]:
obj.index #like range

RangeIndex(start=0, stop=4, step=1)

In [5]:
# to create a series with an index identifying each data point with a label

obj2 = pd.Series([-1,-2,3,4], index=['a','b','c','d'])

obj2

a   -1
b   -2
c    3
d    4
dtype: int64

In [6]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [7]:
# can use labels in the index when selecting values
obj2['a']

-1

In [8]:
obj2[['a','b','c']]

a   -1
b   -2
c    3
dtype: int64

In [9]:
# using NumPy functions or NumPy like operations, preserves the index value link

obj2[obj2 > 0]

c    3
d    4
dtype: int64

In [10]:
obj2*2

a   -2
b   -4
c    6
d    8
dtype: int64

In [11]:
np.exp(obj2)

a     0.367879
b     0.135335
c    20.085537
d    54.598150
dtype: float64

In [12]:
#like a dict
'b' in obj2

True

In [13]:
'e' in obj2

False

In [14]:
# if you have a dict
sdata = {'Arizona': 35000, 'Maryland': 71000, 'Massachusetts': 16000, 'Utah': 5000}

obj3 = pd.Series(sdata)

obj3

Arizona          35000
Maryland         71000
Massachusetts    16000
Utah              5000
dtype: int64

In [15]:
# when passing a dict, the index will have the dict's keys in sorted order
# to override and pass dict keys in order you want

states = ['California', 'Arizona', 'Utah', 'Texas']

obj4 = pd.Series(sdata, index=states)

obj4

California        NaN
Arizona       35000.0
Utah           5000.0
Texas             NaN
dtype: float64

In [16]:
# to detect missing values

pd.isnull(obj4)

California     True
Arizona       False
Utah          False
Texas          True
dtype: bool

In [17]:
pd.notnull(obj4)

California    False
Arizona        True
Utah           True
Texas         False
dtype: bool

In [18]:
obj4.isnull()

California     True
Arizona       False
Utah          False
Texas          True
dtype: bool

In [19]:
# Series automatically aligns by index label in arithmetic operations

obj3

Arizona          35000
Maryland         71000
Massachusetts    16000
Utah              5000
dtype: int64

In [20]:
obj4

California        NaN
Arizona       35000.0
Utah           5000.0
Texas             NaN
dtype: float64

In [21]:
# missing values returns NaN
obj3 + obj4

Arizona          70000.0
California           NaN
Maryland             NaN
Massachusetts        NaN
Texas                NaN
Utah             10000.0
dtype: float64

In [22]:
obj4.name = 'population'

obj4.index.name= 'state'

obj4

state
California        NaN
Arizona       35000.0
Utah           5000.0
Texas             NaN
Name: population, dtype: float64

In [23]:
# series's index changed in-place by assignment

obj

0   -1
1   -2
2    3
3    4
dtype: int64

In [24]:
obj.index = ['Ken','Jane','Bob','Steve']

In [25]:
obj

Ken     -1
Jane    -2
Bob      3
Steve    4
dtype: int64

## Dataframe

Rectangular table of data and contains an ordered collection of columns, which can be of a different type (numeric, string, boolean, etc.) 
* Dataframe has both a row and column index, like a dict of Series all sharing the same index
* stored as one/two-dimensional blocks

In [26]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [27]:
# displayed as an html table

frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [28]:
# if you specify a sequence of columns, the DataFrame's columns will be arranged in that order

pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [29]:
#pass a column not contained in the dict, it will appear with missing values

frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],index=['one', 'two', 'three', 'four','five', 'six'])

In [30]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [31]:
#column in a DataFrame can be retrieved as a Series either by dict-like notation or by attribute
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [32]:
# dict notation
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [33]:
# attribute
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [34]:
# rows can be retrieved position, name, or loc attribute (more later)
frame2


year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [35]:

frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [36]:
# columns can be modified by assignment

frame2['debt'] = 16.5

In [37]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [38]:
frame2['debt']= np.arange(6.0)

frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [39]:
# when assigning lists or arrays to a column, value's length must match the DataFrame
# if you assign a Series, its labels will be realigned exactly to the DataFrame's index
# with missing values labeled as NaN

val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

frame2['debt'] = val

frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [40]:
# assigning a column that doesn't exist will creaet a new column

frame2['eastern'] = frame2.state == 'Ohio'

frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [41]:
# del keyword will delete columns as with a dict

del frame2['eastern']

frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [42]:
# nested 

pop = {'Nevada': {2001: 2.4, 2002: 2.9},'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

frame3= pd.DataFrame(pop)

frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [43]:
# to tranpose

frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [44]:
# keys in the inner dicts are combined to form the index in the result
# unless an explicit index is specified

pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [45]:
# Dict of Series are treated the same

pdata = {'Ohio': frame3['Ohio'][:-1],'Nevada': frame3['Nevada'][:2]}

pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [46]:
# if a DataFrame's index ande columns have their name attributes set, these will also be displayed

frame3.index.name = 'year'; frame3.columns.name = 'state'

frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [47]:
# similar to series, the values attribute returns the data contained in the DataFrame as 2d array

frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [48]:
# if column values are different dtypes, the dtype of the values array will be chosen

frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [49]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### Index Objects

Holds the axis labels and other metadata (axis name or names). Any array or other sequence of labels you use when constructing a Series or DataFrame is internally converted to an Index.

In [50]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [51]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [52]:
index[1:]

Index(['b', 'c'], dtype='object')

In [53]:
index[1]

'b'

In [54]:
# immutability makes it safer to share Index objects among data structures

labels = pd.Index(np.arange(3))

labels

Int64Index([0, 1, 2], dtype='int64')

In [55]:
obj2 = pd.Series([1.5,-2.5,0])

obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [56]:
obj2.index is labels

False

In [57]:
# index behaves like an array and a fixed-size set

frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [58]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [59]:
'Ohio' in frame3.columns

True

In [60]:
2003 in frame3.index

False

In [61]:
# pandas Index can contain duplicate labels, unlike sets

dup_labels = pd.Index(['whoo', 'whoo', 'major', 'major'])

dup_labels

Index(['whoo', 'whoo', 'major', 'major'], dtype='object')

### Essential functionality

In [62]:
# reindex, create a new object with data conformed to a new index

obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [63]:
# reindex rearranges the data according to the new index, introducing missing values if any index values were not present

obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [64]:
# to fill in values when reindexing

obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

obj3

0      blue
2    purple
4    yellow
dtype: object

In [65]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [66]:
# reindex can alter rows or columns or both, 
# when passed as a sequence it reindexes the rows in the result

frame = pd.DataFrame(np.arange(9).reshape((3, 3)),index=['a', 'c', 'd'],columns=['Ohio', 'Texas', 'California'])

frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [67]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [68]:
# reindexed using the columns keyword

states = ['Texas', 'Utah', 'California']

frame.reindex(columns= states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [69]:
# reindex using label-indexing with loc

frame.loc[['a', 'b', 'c', 'd'], states]

C:\Users\kenai\Anaconda3\lib\site-packages\pandas\core\indexing.py:1418: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [81]:
# dropping entries from an Axis

obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [82]:
new_obj = obj.drop('c')

new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [83]:
# using drop the original series is unchanged
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [84]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [85]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [90]:
# use inplace, to change object permanently
obj.drop('c', inplace=True)

obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [86]:
# with a DataFrame, index values can be deleted from either axis

data = pd.DataFrame(np.arange(16).reshape((4, 4)), index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [87]:
# calling drop with a sequence of labels will drop values from the rows (Axis 0)

data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [88]:
# drop daat from the columns by passing axis=1 or axis='columns'

data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [89]:
# functions like drop, modify the size or shape of a Series or DataFrame manipulate the object in place
# does not return a new object

obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

obj


a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

### Indexing, Selection, and Filtering

In [91]:
#series indexing obj[...] works just like NumPy array indexing, except you use the Series's index value
# instead of integers

obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [92]:
obj['b']

1.0

In [93]:
obj[1]

1.0

In [94]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [95]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [96]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [97]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [98]:
# Slicing with labels is different than normal Python
# end-point is inclusive

obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [101]:
# Setting using these methods modifies the section of the Series

obj['b':'c'] = 5

obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [104]:
# Indexing into a DataFrame is for retrieving one or more columns either with a single value or sequence

data = pd.DataFrame(np.arange(16).reshape((4, 4)),index=['Ohio', 'Colorado', 'Utah', 'New York'],
columns=['one', 'two', 'three', 'four'])

data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [105]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [107]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [108]:
# special cases with a boolean array

data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [109]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [110]:
# Boolean comparison
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [113]:
data[data < 5] = 0

data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [114]:
### selection with loc and iloc

# row colorado, columns two and three

data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [116]:
# look at row 2
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [115]:
# look at row 2, columns 3,0,1
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [117]:
# row 1 & 2, columns 3,0,1
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [119]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [118]:
# indexing functions work with slices in addition to single labels or lists of labels

data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [120]:
### Integer Indexes

ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [121]:
# this causes an error
ser[-1]

KeyError: -1

In [123]:
# by using a non-integer index no potential for ambiguity

ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [124]:
ser2[-1]

2.0

In [125]:
# common practice for an axis containing integers, data selection is label-oriented
# use loc for labels or iloc for integers

ser[:1]

0    0.0
dtype: float64

In [126]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [127]:
ser.iloc[:1]

0    0.0
dtype: float64

### Arithmetic and Data Alignment

When adding together objects, if index pairs are not the same, the index will be the union of the index pairs. 

In [128]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],index=['a', 'c', 'e', 'f', 'g'])

In [129]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [130]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [131]:
# missing values in label locations that don't overlap

s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [132]:
# DataFrame, alignment is performed on both the rows and the columns
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])

df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [133]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [134]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [135]:
# union of each dataframe, but NaN in place for any row or column with a missing element
# c,d,e columns are all missing
# rows Oregon, and Utah
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [136]:
# If you add DataFrame objects with no column or row labels in common, the result will contain all nulls

df1 = pd.DataFrame({'A': [1, 2]})

df2 = pd.DataFrame({'B': [3, 4]})

df1

A
0  1
1  2

In [137]:
df2

B
0  3
1  4

In [138]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

### Arithmetic methods with fill values

In [139]:


df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))

df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))

In [140]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [141]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [142]:
# Na in locations which don't overlap
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [143]:
# fill value
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [144]:
# flexible arithmetic methods

1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [145]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [146]:
# when reindexing you can specify a different fill value
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [148]:
### Operations between DataFrame and Series

arr= np.arange(12.).reshape((3,4))

#DataFrame
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [149]:
#series
arr[0]

array([0., 1., 2., 3.])

In [150]:
# subtraction of arr[0] from arr performed once for each row
# also called broadcasting
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [151]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [153]:
series = frame.iloc[0]

frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [154]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [155]:
# by default arithmetic between DataFrame and Series mathces the index of the Series on the DataFrame's columns
# i.e. broadcasting down the rows

frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [156]:
# if value is not found in either the DataFrame's columnsor the Series's index, objects will be 
# reindexed to form the union

series2 = pd.Series(range(3), index = ['b','e','f'])

series2

b    0
e    1
f    2
dtype: int64

In [157]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [158]:
# to broadcast over the columns
# matching on rows, have to use the arithmetic methods

series3= frame['d']

frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [159]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [160]:
# the axis number you pass is the axis to match on, match DataFrame's row index (axis= 'index' or axis= 0)
# then broadcast across
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Universal functions, function application and mapping

In [162]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [163]:
frame

b         d         e
Utah    0.625498  0.582842 -1.098380
Ohio    0.579751  0.733485 -0.927792
Texas  -1.659644 -1.188804 -0.187700
Oregon -0.471639  1.564433  0.264723

In [165]:
# applying a function on one-dimensional arrays to each column or row
# f computes the difference between the max and min of a series
# frame is the index

f = lambda x: x.max() - x.min()

frame.apply(f)

b    2.285142
d    2.753237
e    1.363103
dtype: float64

In [166]:
# if you pass 'columns' to apply, the function will be invoked once per row

frame.apply(f, axis='columns')

Utah      1.723879
Ohio      1.661277
Texas     1.471943
Oregon    2.036071
dtype: float64

In [167]:
# most common array statistics like sum and mean are DataFrame methods, so using apply is not necessary

# function passed to apply doesn't need to return a scalar value, also return a Series with multiple values

def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

frame.apply(f)

b         d         e
min -1.659644 -1.188804 -1.098380
max  0.625498  1.564433  0.264723

In [168]:
#  element-wise python functions can be used too
# compute a formatted string from each floating point value in frame

format = lambda x: '%.2f' % x

frame.applymap(format)

b      d      e
Utah     0.63   0.58  -1.10
Ohio     0.58   0.73  -0.93
Texas   -1.66  -1.19  -0.19
Oregon  -0.47   1.56   0.26

In [170]:
frame['e'].map(format)

Utah      -1.10
Ohio      -0.93
Texas     -0.19
Oregon     0.26
Name: e, dtype: object

### Sorting and Ranking

In [174]:
# use sort_index
# Series

obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

obj

d    0
a    1
b    2
c    3
dtype: int64

In [175]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [173]:
# DataFrame
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),index=['three', 'one'], columns=['d', 'a', 'b', 'c'])

frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [176]:
# sort by rows
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [177]:
# sort by columns
frame.sort_index(axis =1 )

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [178]:
# default is ascending order, to switch to descending order

frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [180]:
# to sort series by its values, use its sort_values

obj = pd.Series([4, 7, -3, 2])


obj

0    4
1    7
2   -3
3    2
dtype: int64

In [181]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [182]:
# missing values are sorted to the end of the series by default

obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [183]:
# use the data in one or more columsn as the sort keys
# pass one or more column names to the by option of sort_values

frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [184]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [191]:
# by rank, lowest number 1, index 5, rank 1

obj = pd.Series([7,6,5,4,2,1,3])

obj

0    7
1    6
2    5
3    4
4    2
5    1
6    3
dtype: int64

In [192]:
# by rank
# index 0 has the largest value = 7, in ascending order rank 7
#index 5, has the lowest value =1, in ascending order rank 1

obj.rank()

0    7.0
1    6.0
2    5.0
3    4.0
4    2.0
5    1.0
6    3.0
dtype: float64

In [190]:
# ranks by order in data
obj.rank(method='first')

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    7.0
dtype: float64

In [193]:
# rank by descending order

obj.rank(ascending=False, method='max')

0    1.0
1    2.0
2    3.0
3    4.0
4    6.0
5    7.0
6    5.0
dtype: float64

In [195]:
# DataFrame compute ranks over rows or columns

frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],'c': [-2, 5, 8, -2.5]})

frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [196]:
# ranked from lowest number =1, to highest number = 3
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### Summarizing and Computing Descriptive Statistics

Mostly reductions or summary statistics, methods that extract a single value (i.e. sum or mean) from a Series or a Series of values from the rows or columns of a DataFrame. Have built in handling for missing data

In [197]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], index=['a', 'b', 'c', 'd'], 
                  columns=['one', 'two'])

df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [198]:
# column total
df.sum()

one    9.25
two   -5.80
dtype: float64

In [199]:
# across columns or the rows
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [200]:
# NA values are excluded unless the entire slice is NA
# can be disabled with the skipna option

df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [202]:
# indirect statistics like index value where min or max occurred

df.idxmax()

one    b
two    d
dtype: object

In [203]:
# cumsum() : adding down the column, or accumulation
# e.g. one= 1.40 + 7.10 + 0.75 

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [204]:
# multiple summary statistics in one shot
#numeric data
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [205]:
#non-numeric data
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### Correlation and Covariance

In [208]:
# using data from the web
conda install pandas-datareader

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\kenai\Anaconda3

  added / updated specs:
    - pandas-datareader


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.8.3                |           py37_0         2.8 MB
    pandas-datareader-0.8.1    |             py_0          71 KB
    ------------------------------------------------------------
                                           Total:         2.9 MB

The following NEW packages will be INSTALLED:

  pandas-datareader  pkgs/main/noarch::pandas-datareader-0.8.1-py_0

The following packages will be UPDATED:

  conda                                       4.7.12-py37_0 --> 4.8.3-py37_0




conda-4.8.3          | 2.8 MB    |            |   0% 
conda-4.8.3          | 2.8 MB    |            |   1% 
conda-4.8.3          | 2.8 MB    | ########## | 100% 

pandas-datareader-0. | 71 KB    

In [209]:
import pandas_datareader.data as web
all_data = {ticker: web.get_data_yahoo(ticker)
    for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [211]:
price = pd.DataFrame({ticker: data['Adj Close']for ticker, data in all_data.items()})

In [212]:
volume = pd.DataFrame({ticker: data['Volume'] for ticker, data in all_data.items()})

In [213]:
returns = price.pct_change()

In [214]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2020-03-25 -0.005509  0.003508 -0.009573 -0.028181
2020-03-26  0.052623  0.066509  0.062551  0.053751
2020-03-27 -0.041402 -0.043051 -0.041061 -0.043934
2020-03-30  0.028538  0.045358  0.070341  0.032511
2020-03-31  0.000628 -0.008235 -0.003589  0.017317

In [215]:
# Correlation method of Series computes correlation of overlapping non-NA, aligned-by-Index alues in two sseries

returns['MSFT'].corr(returns['IBM'])

0.5883385273809344

In [216]:
# cov computes the covariance

returns['MSFT'].cov(returns['IBM'])

0.00015274102670463454

In [217]:
returns.MSFT.corr(returns.IBM)

0.5883385273809344

In [218]:
# DataFrame methodsd return a full correlation or covariance matrix

returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.522010  0.688758  0.628243
IBM   0.522010  1.000000  0.588339  0.515693
MSFT  0.688758  0.588339  1.000000  0.738556
GOOG  0.628243  0.515693  0.738556  1.000000

In [219]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000315  0.000141  0.000209  0.000185
IBM   0.000141  0.000230  0.000153  0.000130
MSFT  0.000209  0.000153  0.000293  0.000210
GOOG  0.000185  0.000130  0.000210  0.000276

In [220]:
# to compute pairwise correlations

returns.corrwith(returns.IBM)

AAPL    0.522010
IBM     1.000000
MSFT    0.588339
GOOG    0.515693
dtype: float64

In [221]:
# passing a DataFrame computes the correlations of matching column names
# correlations of percent change with volume

returns.corrwith(volume)

AAPL   -0.145531
IBM    -0.103927
MSFT   -0.039697
GOOG   -0.046881
dtype: float64

### Unique Values, Value counts, and Membership

In [223]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [224]:
uniques = obj.unique()

# not returned in sorted order
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [225]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [226]:
# value_counts can be used with any array or sequence:

pd.value_counts(obj.values, sort= False)

b    2
c    3
a    3
d    1
dtype: int64

In [227]:
# membership check for filtering a dataset

obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [229]:
mask = obj.isin(['b', 'c'])

mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [230]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [234]:
# relateed is Index.get_indexer which gives you an array from an array of possibly non-distinct values into another
# array of distinct values

# 0 = c, 2 = a, 1 = b

to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

unique_vals = pd.Series(['c', 'b', 'a'])

pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

### Histogram from counts

In [236]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],'Qu2': [2, 3, 1, 2, 3],'Qu3': [1, 5, 2, 4, 4]})

data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [238]:
result = data.apply(pd.value_counts).fillna(0)

# distinct value labels, e.g. in column Qu1 there is 1 1, 0 2's, 2 3's, 2 4's, 0 5's
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0