In [2]:
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
from pylab import *

[Cheat sheet for NumPy basics](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

## From lists to arrays

In [ ]:
# list of data
data = [[11, 22],[33, 44],[55, 66]]
# array of data
data = array(data)
print(data)
print(type(data))

print('Rows: %d' % data.shape[0])
print('Cols: %d' % data.shape[1])

In [ ]:
data=array([0,1,2,3,4,5])
print(array)
print("\n memory address of the first byte in the array:\n", data.data)
print("\n shape of the array:\n",data.shape)
print("\n kind of elements in the array:\n", data.dtype)
print("\n the number of bytes that should be skipped in memory to go to the next element :\n", data.strides)
print("\n the number of array elements :\n", data.size)
print("\n number of array dimensions :\n", data.ndim)
print("\n length of array :\n", len(data))

In [ ]:
data = array([[0,1,2],
[3,4,5]])
print(data)
print("\n shape of the array, rows by columns:\n",data.shape)

In [ ]:
data = np.array([[1,2],[3,4]])
print(array)
print("\n memory address of the first byte in the array:\n", data.data)
print("\n shape of the array:\n",data.shape)
print("\n kind of elements in the array:\n", data.dtype)
print("\n the number of bytes that should be skipped in memory to go to the next element :\n", data.strides)
print("\n the number of array elements :\n", data.size)
print("\n number of array dimensions :\n", data.ndim)
print("\n length of array :\n", len(data))

In [ ]:
print(data)
data = array([[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
print("\n shape of the array:\n",data.shape)

### How to create a sequence of numbers or sequential array

`numpy.linespace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)[source]`

* Return evenly spaced numbers over a specified interval.

* Returns num evenly spaced samples, calculated over the interval [start, stop].

* The endpoint of the interval can optionally be excluded.

In [ ]:
#Create a sequence of integers, where you provide all the numbers
anotherarray = np.array([1,2,3,4,5,6,7,8,9])
print(anotherarray)

In [ ]:
# Create a sequence of integers 
# from 0 to 30 with steps of 5 
f = np.arange(0, 30, 5) 
print ("\nA sequential array with steps of 5:\n", f) 

In [ ]:
# Create a sequence of 10 values in range 0 to 5 
g = np.linspace(0, 5, 10) 
print ("\nA sequential array with 10 values between"
										" 0 and 5:\n", g) 

In [ ]:
t = np.arange(0.0, 2.0, 0.01)
print(t)

In [ ]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

In [ ]:
np.linspace(2.0, 3.0, num=5, endpoint=True)

### How to create a two-dimensional array

In [ ]:
# basic array characteristics 
  
# Creating array object 
arr = np.array( [[ 1, 2, 3], 
                 [ 4, 2, 5]] ) 
  
# Printing type of arr object 
print("Array is of type: ", type(arr)) 
  
# Printing array dimensions (axes) 
print("No. of dimensions: ", arr.ndim) 
  
# Printing shape of array 
print("Shape of array: ", arr.shape) 
  
# Printing size (total number of elements) of array 
print("Size of array: ", arr.size) 
  
# Printing type of elements in array 
print("Array stores elements of type: ", arr.dtype) 

In [ ]:
# Python program to demonstrate 
# array creation techniques 
import numpy as np 

# Creating array from list with type float 
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float') 
print ("Array created using passed list:\n", a) 

In [ ]:
# Creating array from tuple 
b = np.array((1 , 3, 2)) 
print ("\nArray created using passed tuple:\n", b) 

In [ ]:
# Creating a 3X4 array with all zeros 
c = np.zeros((3, 4)) 
print ("\nAn array initialized with all zeros:\n", c) 


In [ ]:
# Create a constant value array of complex type 
d = np.full((3, 3), 6, dtype = 'complex') 
print ("\nAn array initialized with all 6s."
			"Array type is complex:\n", d) 

In [ ]:
# Create an array with random values 
e = np.random.random((2, 2)) 
print ("\nA random array:\n", e) 

In [ ]:
# Reshaping 3X4 array to 2X2X3 array 
arr = np.array([[1, 2, 3, 4], 
				[5, 2, 4, 2], 
				[1, 2, 0, 1]]) 

newarr = arr.reshape(2, 2, 3) 

print ("\nOriginal array:\n", arr) 
print ("Reshaped array:\n", newarr) 

In [ ]:
# Flatten array 
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
flarr = arr.flatten() 

print ("\nOriginal array:\n", arr) 
print ("Flattened array:\n", flarr) 


In [ ]:
# array 
arr = np.array([[-1, 2, 0, 4], 
                [4, -0.5, 6, 0], 
                [2.6, 0, 7, 8], 
                [3, -7, 4, 2.0]]) 

print(arr)

# Slicing array 

print("value at 0,0 :\n", arr[0,0])

print("first row:\n", arr[0])

print("first column:\n", arr[,0])




temp = arr[:2, ::2] 
print ("Array with first 2 rows and alternate "
                    "columns(0 and 2):\n", temp) 

In [ ]:
# Integer array indexing example 
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]] 
print ("\nElements at indices (0, 3), (1, 2), (2, 1),"
                                    "(3, 0):\n", temp) 

In [ ]:
cond = arr > 0 # cond is a boolean array 
temp = arr[cond] 
print ("\nElements greater than 0:\n", temp) 

### Basic operations on arrays

* np.insert(), np.delete()
* np.add(), np.subtract(), np.multiply(), np.divide() and np.remainder().
* np.exp() and np.sqrt(), or calculate the sines or cosines of your array with np.sin() and np.cos(). 
* np.log() or calculate the dot product by applying the dot() to your array.


In [ ]:
np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])


In [ ]:
# permanant change to array
np.append(data, 10)

In [ ]:
#permanent change to array
np.delete(data,4)

In [ ]:
# does not change the array permanently
np.add(data,1)

In [ ]:
# does not change the array permanently
np.subtract(data,1)

In [ ]:
np.log10(data)

### Basic operations on arrays short

In [ ]:
a = np.array([1, 2, 5, 3]) 
  
# add 1 to every element 
print ("Adding 1 to every element:", a+1) 
  
# subtract 3 from each element 
print ("Subtracting 3 from each element:", a-3) 
  
# multiply each element by 10 
print ("Multiplying each element by 10:", a*10) 
  
# square each element 
print ("Squaring each element:", a**2) 
  
# modify existing array 
a *= 2
print ("Doubled each element of original array:", a) 
  
# to create transpose of array 
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]]) 
  
print ("\nOriginal array:\n", a) 
print ("Transpose of array:\n", a.T) 

### Array Comparison

In [ ]:
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
b = a.T

print(a)

print("\n",b)

a == b

In [ ]:
a < 2

In [ ]:
np.array_equal(a,b)

### Aggregate functions on the entire array

* rows are axis 0
* columns are axis 1

In [ ]:
a = np.array([0,1,2,3,4,5]) 

print(a)
print("\n sum of one-d array:\n",np.sum(a))

b = np.array([[7,8,9],[1,3,5]])

print("\n sum of two-d array:\n",np.sum(b))


In [ ]:
# to sum down all the rows or the just the columns
c = np.array([[0,1,2], [0,1,2], [0,1,2]])
print(c)

np.sum(c, axis=0)

In [ ]:
# to sum across the columns or just the rows
c = np.array([[0,1,2], [0,1,2], [0,1,2]])
print(c)

np.sum(c, axis=1)

In [ ]:
# Python program to demonstrate 
# unary operators in numpy 
import numpy as np 
  
arr = np.array([[1, 5, 6], 
                [4, 7, 2], 
                [3, 1, 9]]) 
  
# maximum element of array 
print ("Largest element is:", arr.max()) 
print ("Row-wise maximum elements:", 
                    arr.max(axis = 1)) 
  
# minimum element of array 
print ("Column-wise minimum elements:", 
                        arr.min(axis = 0)) 
  
# sum of array elements 
print ("Sum of all array elements:", 
                            arr.sum()) 
  
# cumulative sum along each row 
print ("Cumulative sum along each row:\n", 
                        arr.cumsum(axis = 1)) 

In [ ]:
# Python program to demonstrate 
# binary operators in Numpy 
import numpy as np 
  
a = np.array([[1, 2], 
            [3, 4]]) 
b = np.array([[4, 3], 
            [2, 1]]) 
  
# add arrays 
print ("Array sum:\n", a + b) 
  
# multiply arrays (elementwise multiplication) 
print ("Array multiplication:\n", a*b) 
  
# matrix multiplication 
print ("Matrix multiplication:\n", a.dot(b)) 

In [ ]:
# Python program to demonstrate 
# universal functions in numpy 
import numpy as np 
  
# create an array of sine values 
a = np.array([0, np.pi/2, np.pi]) 
print ("Sine values of array elements:", np.sin(a)) 
  
# exponential values 
a = np.array([0, 1, 2, 3]) 
print ("Exponent of array elements:", np.exp(a)) 
  
# square root of array values 
print ("Square root of array elements:", np.sqrt(a)) 

In [ ]:
# Python program to demonstrate sorting in numpy 
import numpy as np 
  
a = np.array([[1, 4, 2], 
                 [3, 4, 6], 
              [0, -1, 5]]) 
  
# sorted array 
print ("Array elements in sorted order:\n", 
                    np.sort(a, axis = None)) 
  
# sort array row-wise 
print ("Row-wise sorted array:\n", 
                np.sort(a, axis = 1)) 
  
# specify sort algorithm 
print ("Column wise sort by applying merge-sort:\n", 
            np.sort(a, axis = 0, kind = 'mergesort')) 
  
# Example to show sorting of structured array 
# set alias names for dtypes 
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)] 
  
# Values to be put in array 
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7),  
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)] 
             
# Creating array 
arr = np.array(values, dtype = dtypes) 
print ("\nArray sorted by names:\n", 
            np.sort(arr, order = 'name')) 
              
print ("Array sorted by grauation year and then cgpa:\n", 
                np.sort(arr, order = ['grad_year', 'cgpa'])) 


### One Dimensional indexing

Use the bracket `[]` operator

In [ ]:
data = array([1,2,3,4,5])

print(data[0])
print(data[4])

In [ ]:
# indexing too large for the bound will come up with an error

print(data[5])

In [ ]:
# you can use negative indexes
print(data)

print("\n last item:\n",data[-1])
print("\n first item:\n",data[-5])

## Two-Dimensional Indexing

Use a `,` to separate the index for each dimension

In [ ]:
data = [[11, 22],[33, 44],[55, 66]]
# array of data
data = array(data)
print(data)

print("\n first item:\n",data[0,0])

In [ ]:
# all items in first row

print(data[0,])

## Array Slicing

* Structures like lists and NumPy arrays can be sliced, and can be indexed and retrieved
* slicing uses `:` indicating _from_ `:` _t_o before and after the column
* the slice extends from the from index and ends one item before the to index

### One dimensional slicing

In [ ]:
data = array([0,1,2,3,4,5])
print(data[:])

In [ ]:
print("\n from 0 and ends before 1:\n",data[0:1])

In [ ]:
#negative index works too

print("\n last item :\n", data[-1:])

### Two dimensional slicing

* Input (x) and output (y) variables
* slicing all rows and all columns up to, but before the last column, then separately indexing the last column
* for input features, we can select all rows and all columns except the last one by specifying `:` for the rows index
* and `:-1` in the columns index
\n

`
X = [:,:-1]
y = [:, -1]
`

In [ ]:
data = array([[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
X, y = data[:, :-1], data[:, -1]
print("\n this is X, a two dimensional array :\n",X)
print("\n this is y, a one dimensional array :\n", y)

### Split training and test rows

* common to have smaller sample dataset to train a model
* larger or full dataset used to test model

In [ ]:
data = array([[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
split = 2
train,test = data[:split,:],data[split:,:]
print("\n this is the training data :\n", train)
print("\n this is the test data :\n", test)

### Reshaping one-dimensional array to two-dimensional array

* use the `reshape()` function

### Reshaping arrays

* `a.view()` to view the array with the same data
* `np.copy()` to create a copy of the array
    * A shallow copy constructs a new compound object and then (to the extent possible) inserts references into it to the objects found in the original.
    * shallow copy means constructing a new collection object and then populating it with references to the child objects found in the original. The copying process does not recurse and therefore won’t create copies of the child objects themselves. In case of shallow copy, a reference of object is copied in other object. It means that any changes made to a copy of object do reflect in the original object.
* `a.copy()` to create a deep copy
     * A deep copy constructs a new compound object and then, recursively, inserts copies into it of the objects found in the original.  
     * Deep copy is a process in which the copying process occurs recursively. It means first constructing a new collection object and then recursively populating it with copies of the child objects found in the original. In case of deep copy, a copy of object is copied in other object. It means that any changes made to a copy of object do not reflect in the original object. In python, this is implemented using “deepcopy()” function.

### Sorting arrays

In [ ]:
data = array([4,3,2,1,6])
print(a.sort(data))

In [ ]:
b = np.array([[7,8,9],[1,3,5]])
c.sort(b,axis =0)

In [ ]:
b = np.array([[7,8,9],[1,3,5]])
c.sort(b,axis =1)

### Stacking in NumPy

* np.vstack: To stack arrays along vertical axis.
* np.hstack: To stack arrays along horizontal axis.
* np.column_stack: To stack 1-D arrays as columns into 2-D arrays.
* np.concatenate: To stack arrays along specified axis (axis is passed as argument).

In [3]:
a = np.array([[1, 2], 
              [3, 4]]) 
  
b = np.array([[5, 6], 
              [7, 8]]) 
  
# vertical stacking 
print("Vertical stacking:\n", np.vstack((a, b))) 
  
# horizontal stacking 
print("\nHorizontal stacking:\n", np.hstack((a, b))) 
  
c = [5, 6] 
  
# stacking columns 
print("\nColumn stacking:\n", np.column_stack((a, c))) 
  
# concatenation method  
print("\nConcatenating to 2nd axis:\n", np.concatenate((a, b), 1)) 


Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]

Column stacking:
 [[1 2 5]
 [3 4 6]]

Concatenating to 2nd axis:
 [[1 2 5 6]
 [3 4 7 8]]


### Splitting in NumPy

* np.hsplit: Split array along horizontal axis.
* np.vsplit: Split array along vertical axis.
* np.array_split: Split array along specified axis.

In [4]:
import numpy as np 
  
a = np.array([[1, 3, 5, 7, 9, 11], 
              [2, 4, 6, 8, 10, 12]]) 
  
# horizontal splitting 
print("Splitting along horizontal axis into 2 parts:\n", np.hsplit(a, 2)) 
  
# vertical splitting 
print("\nSplitting along vertical axis into 2 parts:\n", np.vsplit(a, 2))

Splitting along horizontal axis into 2 parts:
 [array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]

Splitting along vertical axis into 2 parts:
 [array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]


### Broadcasting in NumPY

* simplest example: array and a scalar value are combined in an operation
* Broadcasting: The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.
* Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are also cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.

* NumPy operations are usually done element-by-element which requires two arrays to have exactly the same shape. Numpy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints.

In [ ]:
import numpy as np 
  
a = np.array([1.0, 2.0, 3.0]) 
  
# Example 1 
b = 2.0
print(a * b) 
  
# Example 2 
c = [2.0, 2.0, 2.0] 
print(a * c)

In [ ]:
# both arrays are stretched

import numpy as np 
  
a = np.array([0.0, 10.0, 20.0, 30.0]) 
b = np.array([0.0, 1.0, 2.0]) 
  
print(a[:, np.newaxis] + b)

In [ ]:
### Working with datetime

# creating a date 
today = np.datetime64('2020-03-25') 
print("Date is:", today) 
print("Year is:", np.datetime64(today, 'Y')) 
  
# creating array of dates in a month 
dates = np.arange('2020-02', '2020-03', dtype='datetime64[D]') 
print("\nDates of February, 2020:\n", dates) 
print("Today is February:", today in dates) 
  
# arithmetic operation on dates 
dur = np.datetime64('2017-05-22') - np.datetime64('2016-05-22') 
print("\nNo. of days:", dur) 
print("No. of weeks:", np.timedelta64(dur, 'W')) 
  
# sorting dates 
a = np.array(['2017-02-12', '2016-10-13', '2019-05-22'], dtype='datetime64') 
print("\nDates in sorted order:", np.sort(a))